#!/usr/bin/env sh
# Install development dependencies with gem

# Bundler
gem install bundler

# Pry stuff
gem install pry
gem install pry-doc

# Pre-Processor(s)
gem install sass

# SASS libraries
gem install compass
gem install bourbon
gem install neat
