language: objective-c

notifications:
  email:
    on_success: never
    on_failure: change
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4d66d4b62e6492c849e2
    on_success: change
    on_failure: always
    on_start: false

env:
  - APM_TEST_PACKAGES="autocomplete-plus"

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

git:
  depth: 10
