#!/usr/bin/env sh
# All the global npm stuff I like

# @visionmedia's n node version manager
npm install -g n

# CoffeeScript
npm install -g coffee-script

# Pre-processors
npm install -g jade
npm install -g stylus

# Nodejitsu's cli
npm install -g jitsu

# Frameworks
npm install -g express
npm install -g geddy

# Front-End
npm install -g spine.app
npm install -g batman

# Utilities
npm install -g hem
npm install -g jake
