#!/usr/bin/env sh

# Update brew
brew update

# Upgrade installed formulas
brew upgrade

# ---"TEH NECESSARIES"---
echo "Homebrew :: Installing neccessary base packages..."
brew install coreutils
brew install grc
brew install gawk
brew install tree
brew install webkit2png
brew install git
brew install jq

# ---Languages---
# Node.js
# the brew node does not install npm, but it can be installed with the following:
# curl http://npmjs.org/install.sh | sh
echo "Homebrew :: Installing node..."
brew install node

# rbenv and ruby-build
echo "Homebrew :: Installing ruby management stuff..."
brew install rbenv
brew install ruby-build

# Scala and Typesafe Stack
echo "Homebrew :: Installing the Type Stack (scala, akka, etc.)..."
brew install scala
brew install sbt
brew install maven
brew install giter8
